import './globals.css'
import { Poppins } from 'next/font/google'
import Header from './components/header';
import Footer from './components/footer';
import { AuthContextProvider, useAuth } from './(auth)/useAuth';

const poppins = Poppins({ 
  weight: ['200', '400', '500' ,'600', '700', '800' ,'900'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Surjapuri Shaadi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`flex flex-col min-h-screen ${poppins.className}`}>
            <AuthContextProvider>
              <Header/>  
                {children}
              <Footer/>
            </AuthContextProvider>
        </body>
      </html>
  )
}